services:
  backend:
    image: node:lts-alpine
    build:
      context: ./
      dockerfile: ${BACKEND_FOLDER}/DOCKERFILE
    working_dir: /app
    command: sh -c "npm i && npm run dev"
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ${BACKEND_FOLDER}:/app

  db:
    image: postgres:16.4-alpine3.20
    restart: always
    volumes:
      - blog-db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  blog-db-data:
